### PR TITLE
added item cost support

### PR DESCRIPTION
**Pull request by weaondara**
this should implement #20

### CODE REVIEW

**Comment by Tackoozle** [comment]
Will this be merged? :)

**Comment by Guillaume-Lebegue** [comment]
Sorry, I'm trying to find time to look at this.

**Comment by Guillaume-Lebegue** [comment]
I think I'll decline it.

Your solution is either Item or money. And I would like to do something like 1000$ and 3 Diamond blocks.

I'm actually thinking about updating the upgrades interfaces to have something like magic cobblestone generator that will allow a neat view when displaying multiple requirements.

And i'm also thinking about adding in game customization like the challenge addon, so config files will change.

**Comment by BONNe** [comment]
Oh... you want too much :D 
GUI for everything :D

**Comment by Guillaume-Lebegue** [comment]
Well, I don't want to put only one type of item or just money. And if I use both, there will be too much information. So I'll surely need an interface for this.

And with this info added, the settings are starting to get really messy, and quite incomprehensible, so some things to make that would be useful.

But well, the second one is a long run one.

**Comment by weaondara** [comment]
> Your solution is either Item or money.
i could change that if you wish
> And if I use both, there will be too much information.
that would only be an extra line in the lore so 3 instead of 2

**Pull request closed without merging**
